[build]
command = "hugo"
publish = "public"
[build.environment]
HUGO_VERSION = "0.80.0"

[context]
[context.branch-deploy]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.deploy-preview]
command = "hugo -F -b $DEPLOY_PRIME_URL"
[context.production]
[context.production.environment]
HUGO_ENV = "production"

[[redirects]]
  from = "https://tidytales-an-introduction-to-statistical-learning.netlify.app"
  to = "/self-study/an-introduction-to-statistical-learning/"
  status = 200
  force = true
